[project]
name = "ludos"
version = "0.0.1"
authors = [
  { name="Kapenekakis Antheas", email="pypi@antheas.dev" },
]
description = "Ludos. An end-to-end tool for building OS images from source."
readme = "readme.md"
license = "AGPL-3.0-or-later"
license-files = ["LICENSE", "COPYRIGHT"]
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: POSIX :: Linux",
]

dependencies = [
  "PyYAML>=6.0.3",
]

[project.optional-dependencies]
pretty = [
  "rich>=15.0.0",
  "tqdm>=4.68.4",
]
images = [
  "boto3>=1.43.49",
  "numpy>=2.5.1",
]
flatpaks = [
  "boto3>=1.43.49",
  "Pillow>=12.3.0",
]
all = [
  "boto3>=1.43.49",
  "numpy>=2.5.1",
  "Pillow>=12.3.0",
  "rich>=15.0.0",
  "tqdm>=4.68.4",
]

[project.urls]
"Homepage" = "https://github.com/anatase-org/ludos"
"Bug Tracker" = "https://github.com/anatase-org/ludos/issues"

[project.entry-points."console_scripts"]
ludos = "ludos.__main__:main"

[build-system]
requires = ["setuptools>=77.0.3", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]  # list of folders that contain the packages (["."] by default)
include = ["ludos*"]  # package names should match these glob patterns (["*"] by default)
