[project]
name = "ludos"
version = "0.0.1"
authors = [
  { name="Kapenekakis Antheas", email="pypi@antheas.dev" },
]
description = "Ludos. An end-to-end tool for building OS images from source."
readme = "readme.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: POSIX :: Linux",
]

dependencies = [
  "PyYAML>=6.0.1",
  "rich>=13.5.2",
  "numpy>=2.0.0",
  "tqdm>=4.66.4",
]

[project.urls]
"Homepage" = "https://github.com/anatase-org/ludos"
"Bug Tracker" = "https://github.com/anatase-org/ludos/issues"

[project.entry-points."console_scripts"]
ludos = "ludos.__main__:main"
rechunk = "rechunk.__main__:main"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]  # list of folders that contain the packages (["."] by default)
include = ["ludos*", "rechunk*"]  # package names should match these glob patterns (["*"] by default)
